AWSTemplateFormatVersion: 2010-09-09
Description: >-
  AWS CloudFormation Sample Template EasyVPN_Client
  create a stack from this template.
Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  InstanceType:
    Description: EasyClient EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - c4.large
    ConstraintDescription: must be a valid EC2 instance type.
  VpcId:
    Type: 'AWS::EC2::VPC::Id'
    Description: VpcId of your existing Virtual Private Cloud (VPC)
    ConstraintDescription: must be the VPC Id of an existing Virtual Private Cloud.
  VpcCIDR:
    Description: VPC CIDR
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
  SubnetId:
    Type: 'AWS::EC2::Subnet::Id'
    Description: SubnetId of an existing public subnet in your Virtual Private Cloud (VPC)
    ConstraintDescription: must be an existing public subnet in the selected Virtual Private Cloud.
  SSHLocation:
    Description: The IP address range that can be used to SSH to the EC2 instances
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
  VPNServerIP:
    Description: The IP address of remote VPN Server EIP
    Type: String
    MinLength: '7'
    MaxLength: '15'
    Default: 0.0.0.0
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})'
    ConstraintDescription: Must be a valid IP address
  PSK:
    Description: VPN PSK
    Type: String
    MinLength: '0'
    MaxLength: '512'
    Default: ''
    ConstraintDescription: 512 byte from VPN Server Cloudformation output
Mappings:
  AWSInstanceType2Arch:
    t2.micro:
      Arch: HVM64
    c4.large:
      Arch: HVM64
    c5.large:
      Arch: HVM64
  AWSRegionMap: 
    us-east-1: # Virginia
      HVM64: ami-467ca739
      AWSARN: aws
      DownloadS3Region: us-east-1
      S3Domain: amazonaws.com
    us-east-2: # Ohio
      HVM64: ami-976152f2
      AWSARN: aws
      DownloadS3Region: us-east-1
      S3Domain: amazonaws.com
    us-west-1: # Califonia
      HVM64: ami-46e1f226
      AWSARN: aws
      DownloadS3Region: us-east-1
      S3Domain: amazonaws.com
    us-west-2: # Oregon
      HVM64: ami-6b8cef13
      AWSARN: aws
      DownloadS3Region: us-east-1
      S3Domain: amazonaws.com
    ca-central-1: # Canada
      HVM64: ami-2f39bf4b
      AWSARN: aws
      DownloadS3Region: us-east-1
      S3Domain: amazonaws.com
    eu-west-1: # Ireland
      HVM64: ami-9cbe9be5
      AWSARN: aws
      DownloadS3Region: us-east-1
      S3Domain: amazonaws.com
    eu-west-2: # London
      HVM64: ami-c12dcda6
      AWSARN: aws
      DownloadS3Region: us-east-1
      S3Domain: amazonaws.com
    eu-west-3: # Paris
      HVM64: ami-cae150b7
      AWSARN: aws
      DownloadS3Region: us-east-1
      S3Domain: amazonaws.com
    eu-central-1: # Frankfurt
      HVM64: ami-1b316af0
      AWSARN: aws
      DownloadS3Region: us-east-1
      S3Domain: amazonaws.com
    ap-south-1: # Mumbai
      HVM64: ami-b46f48db
      AWSARN: aws
      DownloadS3Region: us-east-1
      S3Domain: amazonaws.com
    ap-southeast-1: # Sinpapore
      HVM64: ami-64260718
      AWSARN: aws
      DownloadS3Region: us-east-1
      S3Domain: amazonaws.com
    ap-southeast-2: # Sydney
      HVM64: ami-60a26a02
      AWSARN: aws
      DownloadS3Region: us-east-1
      S3Domain: amazonaws.com
    ap-northeast-1: # Tokyo
      HVM64: ami-28ddc154
      AWSARN: aws
      DownloadS3Region: us-east-1
      S3Domain: amazonaws.com
    ap-northeast-2: # Seoul
      HVM64: ami-efaf0181
      AWSARN: aws
      DownloadS3Region: us-east-1
      S3Domain: amazonaws.com
    sa-east-1: # Sao Paulo
      HVM64: ami-f09dcc9c
      AWSARN: aws
      DownloadS3Region: us-east-1
      S3Domain: amazonaws.com
    cn-north-1: # Beijing (China)
      HVM64: ami-d8578bb5
      AWSARN: aws-cn
      DownloadS3Region: cn-northwest-1
      S3Domain: amazonaws.com.cn
    cn-northwest-1: # Ningxia (China) 
      HVM64: ami-02f5e160
      AWSARN: aws-cn
      DownloadS3Region: cn-northwest-1
      S3Domain: amazonaws.com.cn
Resources:
  VPNClientEIP:
    Type: 'AWS::EC2::EIP'
    Properties:
      Domain: vpc
  EIPAssoc1:
    Type: 'AWS::EC2::EIPAssociation'
    Properties:
      NetworkInterfaceId: !Ref Eth0
      AllocationId: !GetAtt 
        - VPNClientEIP
        - AllocationId
  SSHSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      VpcId: !Ref VpcId
      GroupDescription: Enable SSH access via port 22,icmp and VPN Server UDP 81-89, TCP 1200-1300
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: !Ref SSHLocation
        - IpProtocol: udp
          FromPort: '81'
          ToPort: '89'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '1200'
          ToPort: '1300'
          CidrIp: 0.0.0.0/0
        - IpProtocol: icmp
          FromPort: '-1'
          ToPort: '-1'
          CidrIp: 0.0.0.0/0
        - IpProtocol: '-1'
          FromPort: '-1'
          ToPort: '-1'
          CidrIp: !Ref VpcCIDR
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !FindInMap 
        - AWSRegionMap
        - !Ref 'AWS::Region'
        - !FindInMap 
          - AWSInstanceType2Arch
          - !Ref InstanceType
          - Arch
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      NetworkInterfaces:
        - NetworkInterfaceId: !Ref Eth0
          DeviceIndex: '0'
      SourceDestCheck: 'false'
      Tags:
        - Key: Name
          Value: EasyVPNClient
      UserData: 
        Fn::Base64: !Sub
          # Inital EasyVPN Server environment
          - |
            #!/bin/bash -xe
            yum install -y wget
            wget https://s3.${DownloadS3Region}.${S3Domain}/nwcdlabs/templates/easy-vpc-peering/EasyVPN_Client_Setup.sh
            /bin/bash ./EasyVPN_Client_Setup.sh ${VPNServerIP} ${VpcCIDR} ${PSK}
          -
            DownloadS3Region: !FindInMap [ AWSRegionMap, !Ref "AWS::Region", DownloadS3Region ]
            S3Domain: !FindInMap [ AWSRegionMap, !Ref "AWS::Region", S3Domain ]
            VPNServerIP: !Ref VPNServerIP
            VpcCIDR: !Ref VpcCIDR
            PSK: !Ref PSK
  Eth0:
    Type: 'AWS::EC2::NetworkInterface'
    Properties:
      Description: eth0
      GroupSet:
        - !Ref SSHSecurityGroup
      SourceDestCheck: 'true'
      SubnetId: !Ref SubnetId
      Tags:
        - Key: Name
          Value: Interface 0
        - Key: Interface
          Value: eth0
Outputs:
  InstanceId:
    Value: !Ref EC2Instance
    Description: Instance Id of newly created instance
  VPNClientEIP:
    Value: !Ref VPNClientEIP
    Description: VPN Client EIP